# Generated by Django 4.2.1 on 2023-06-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultadoCep',
        ),
        migrations.AddField(
            model_name='cep',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cep',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cep',
            name='service',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='cep',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cep',
            name='street',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
