# Generated by Django 4.2.1 on 2023-06-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_delete_resultadocep_cep_city_cep_neighborhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cep',
            name='cep',
            field=models.CharField(max_length=8),
        ),
    ]
